name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: .github/workflows/fooo.sh
      - name: Tag branch
        run: |
          git tag -f -a test -m "Release ${VERSION}."
          git push -f origin test
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: .github/workflows/work/**/*